// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type User struct {
	ID         int32        `json:"id"`
	Email      string       `json:"email"`
	Name       string       `json:"name"`
	SignupDate sql.NullTime `json:"signup_date"`
	Password   string       `json:"password"`
}
